# Generated by Django 5.0.7 on 2024-07-16 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newslist", "0003_alter_news_title_alter_news_title_en"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={"verbose_name_plural": "News"},
        ),
    ]
