# Generated by Django 5.0.7 on 2024-07-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newslist", "0004_alter_news_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="archive_link",
            field=models.URLField(null=True, verbose_name="URL for archive.org"),
        ),
    ]
