# Generated by Django 5.0.7 on 2024-07-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newslist", "0005_news_archive_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="image",
            field=models.URLField(
                blank=True, null=True, verbose_name="Image of incident if available"
            ),
        ),
    ]
