# Generated by Django 5.0.7 on 2024-07-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newslist", "0006_news_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="is_killed",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
