# Generated by Django 5.0.7 on 2024-07-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newslist", "0007_news_is_killed"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1000, verbose_name="Title")),
                (
                    "location",
                    models.CharField(
                        max_length=100,
                        null=True,
                        verbose_name="Your Location (X University)",
                    ),
                ),
                ("content", models.TextField(verbose_name="Description")),
                ("approved", models.BooleanField(blank=True, default=False)),
            ],
        ),
        migrations.AlterField(
            model_name="news",
            name="is_killed",
            field=models.BooleanField(
                blank=True,
                default=False,
                verbose_name="Is someone has been unalived in this news?: ",
            ),
        ),
    ]
