# Generated by Django 5.0.7 on 2024-07-17 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newslist", "0013_userreport_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={"ordering": ["-id"], "verbose_name_plural": "News"},
        ),
        migrations.AlterModelOptions(
            name="userreport",
            options={"ordering": ["-id"]},
        ),
    ]
