<<<<<<< HEAD
# Generated by Django 5.0.7 on 2024-08-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newslist', '0014_alter_news_options_alter_userreport_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='archive_link',
            field=models.URLField(blank=True, null=True, verbose_name='URL for archive.org'),
        ),
    ]
=======
# Generated by Django 5.0.7 on 2024-08-04 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newslist", "0014_alter_news_options_alter_userreport_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="archive_link",
            field=models.URLField(
                blank=True, null=True, verbose_name="URL for archive.org"
            ),
        ),
    ]
>>>>>>> 22b332aeb532dd930ec59754164121ee5963dddf
