# Generated by Django 5.0.7 on 2024-08-05 21:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("newslist", "0017_alter_martyr_options_martyr_death"),
    ]

    operations = [
        migrations.RenameField("martyr", "description", "short_description"),
    ]
