# Generated by Django 5.0.7 on 2024-08-05 21:16

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("newslist", "0018_auto_20240806_0314"),
    ]

    operations = [
        migrations.AlterField(
            model_name="martyr",
            name="short_description",
            field=tinymce.models.HTMLField(verbose_name="Short Description of martyr"),
        ),
    ]
