# Generated by Django 5.0.7 on 2024-08-05 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newslist", "0020_longdescription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="longdescription",
            name="martyr_model",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="long_description",
                to="newslist.martyr",
            ),
        ),
    ]
