# Generated by Django 5.0.7 on 2024-08-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newslist", "0021_alter_longdescription_martyr_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="martyr",
            name="approved",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="martyr",
            name="birth",
            field=models.DateField(blank=True, null=True, verbose_name="Date of birth"),
        ),
        migrations.DeleteModel(
            name="UserReport",
        ),
    ]
