# Generated by Django 5.0.7 on 2024-08-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newslist", "0022_martyr_approved_martyr_birth_delete_userreport"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="news",
            name="title_en",
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=1000, verbose_name="News title"),
        ),
    ]
