# Generated by Django 5.0.7 on 2024-08-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("newslist", "0023_remove_news_title_en_alter_news_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="approved",
            field=models.BooleanField(
                default=True, verbose_name="Is Approved By admin?: "
            ),
        ),
    ]
