# Generated by Django 5.0.7 on 2024-08-08 23:22

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newslist", "0024_news_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="martyr",
            name="approved",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Indicate whether the martyr's information is approved by an admin.",
            ),
        ),
        migrations.AlterField(
            model_name="martyr",
            name="birth",
            field=models.DateField(
                blank=True,
                help_text="Optional: Enter the birth date of the martyr.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="martyr",
            name="death",
            field=models.DateField(
                blank=True,
                help_text="Optional: Enter the death date of the martyr.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="martyr",
            name="image",
            field=models.URLField(help_text="Provide a URL to an image of the martyr."),
        ),
        migrations.AlterField(
            model_name="martyr",
            name="name",
            field=models.CharField(
                help_text="Enter the full name of the martyr.", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="martyr",
            name="short_description",
            field=tinymce.models.HTMLField(
                help_text="Provide a brief description of the martyr's life and legacy."
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="approved",
            field=models.BooleanField(
                default=False,
                help_text="Indicate whether the news is approved by an admin.",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="archive_link",
            field=models.URLField(
                blank=True,
                help_text="Optional: Provide a link to the archived version of the news.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Optional: Enter a brief description of the news.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="image",
            field=models.URLField(
                blank=True,
                help_text="Optional: Provide a URL to an image related to the news.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="is_killed",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="Check this box if the news relates to a fatal incident.",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="link",
            field=models.URLField(
                help_text="Provide the link to the original news article."
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(
                help_text="Enter the title of the news.", max_length=1000
            ),
        ),
    ]
