# Generated by Django 5.0.7 on 2024-08-10 07:00

from django.db import migrations
import slugify.slugify


def gen_slug(apps, schema_editor):
    MyModel = apps.get_model("newslist", "martyr")
    for row in MyModel.objects.all():
        row.slug = slugify.slugify(row.name + str(row.id))
        row.save(update_fields=["slug"])


class Migration(migrations.Migration):
    dependencies = [
        ("newslist", "0026_martyr_slug"),
    ]

    operations = [migrations.RunPython(gen_slug)]
