# Generated by Django 5.0.7 on 2024-08-10 07:10

import autoslug.fields
import slugify.slugify
from django.db import migrations

import newslist.models


class Migration(migrations.Migration):
    dependencies = [
        ("newslist", "0027_auto_20240810_1300"),
    ]

    operations = [
        migrations.AlterField(
            model_name="martyr",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False,
                populate_from=newslist.models.get_title_and_id,
                slugify=slugify.slugify,
                null=False,
            ),
        ),
    ]
