# Generated by Django 5.1 on 2024-08-11 05:40

import autoslug.fields
import newslist.models
import slugify.slugify
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("newslist", "0028_auto_20240810_1310"),
    ]

    operations = [
        migrations.AlterField(
            model_name="martyr",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False,
                populate_from=newslist.models.get_title_and_id,
                slugify=slugify.slugify,
                unique=True,
            ),
        ),
    ]
