# Generated by Django 5.1 on 2024-08-12 11:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("newslist", "0029_alter_martyr_slug"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BnTag",
        ),
        migrations.DeleteModel(
            name="BnTaggedItem",
        ),
        migrations.RemoveField(
            model_name="news",
            name="tags",
        ),
    ]
