# Generated by Django 5.1 on 2024-08-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newslist", "0030_delete_bntag_delete_bntaggeditem_remove_news_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="published",
            field=models.DateField(
                blank=True,
                help_text="Optional: Enter the date when the news was published.",
                null=True,
            ),
        ),
    ]
