# Generated by Django 5.1 on 2024-08-12 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("newslist", "0031_news_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={"ordering": ["-published", "-id"], "verbose_name_plural": "News"},
        ),
    ]
