# Generated by Django 5.1 on 2024-08-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newslist', '0033_alter_news_archive_link_alter_news_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='martyr',
            name='image',
            field=models.URLField(default='https://i.ibb.co/v3Bbnf5/gray-photo-placeholder.jpg', help_text='Provide a URL to an image of the martyr.'),
        ),
    ]
