# Generated by Django 5.0.7 on 2024-08-02 21:23

import autoslug.fields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=250, verbose_name="A small title for the even."
                    ),
                ),
                (
                    "description",
                    tinymce.models.HTMLField(verbose_name="Description of this event."),
                ),
                ("date", models.DateTimeField(verbose_name="Date of the occerence")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="title"
                    ),
                ),
            ],
        ),
    ]
