# Generated by Django 5.0.7 on 2024-08-02 22:21

import django.utils.timezone
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timeline", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="time",
            field=models.TimeField(
                default=django.utils.timezone.now, verbose_name="Time of incident."
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(verbose_name="Date of the occerence"),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=tinymce.models.HTMLField(verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(
                max_length=250, verbose_name="A small title for the event."
            ),
        ),
    ]
