# Generated by Django 5.0.7 on 2024-08-10 06:48

import autoslug.fields
import timeline.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("timeline", "0005_alter_event_read_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False,
                populate_from=timeline.models.get_title_and_id,
                unique=True,
            ),
        ),
    ]
