# Generated by Django 5.0.7 on 2024-08-10 06:50

import autoslug.fields
import slugify.slugify
from django.db import migrations

import timeline.models


class Migration(migrations.Migration):
    dependencies = [
        ("timeline", "0006_alter_event_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False,
                populate_from=timeline.models.get_title_and_id,
                slugify=slugify.slugify,
                unique=True,
            ),
        ),
    ]
